--- #YAML:1.0
name:               Log-Dispatch-Config
version:            1.03
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AppConfig:      1.52
    File::Temp:     0.12
    IO::Scalar:     0
    Log::Dispatch:  2
    Test::More:     0.32
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
