---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.5707, CPAN::Meta::Converter version 2.110930'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-Config
no_index:
  directory:
    - t
    - inc
requires:
  AppConfig: 1.52
  File::Temp: 0.12
  IO::Scalar: 0
  Log::Dispatch: 2
  Test::More: 0.32
version: 1.04
